build:app:
  image: node:11-alpine
  stage: build
  before_script:
    - apk add python make g++
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  tags:
    - docker

deploy:archive:
  image: ruby:2.4-alpine
  stage: deploy
  before_script:
    - apk add --no-cache zip
  script:
    - mv dist content
    - zip -9 -r content.zip content
  artifacts:
    paths:
      - content.zip
    expire_in: 1 days
    when: always
  dependencies:
    - build:app
  only:
    - master
  tags:
    - docker

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv dist public
  dependencies:
    - build:app
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker
